#!/usr/bin/env pwsh
# ═══════════════════════════════════════════════════════════════════════════
# QANTUM Module Analyzer - Extract Top Enterprise Modules
# ═══════════════════════════════════════════════════════════════════════════

param(
    [int]$TopCount = 50,
    [string[]]$Types = @("God-Tier", "Security", "Core", "FinTech", "Autonomous"),
    [int]$MinLOC = 200
)

Write-Host "🔍 QANTUM Module Analyzer" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# Paths
$reportPath = Join-Path $PSScriptRoot "..\MEGA_AUDIT_REPORT.json"
$outputPath = Join-Path $PSScriptRoot "..\TOP_MODULES.md"

# Check if report exists
if (-not (Test-Path $reportPath)) {
    Write-Host "❌ MEGA_AUDIT_REPORT.json not found!" -ForegroundColor Red
    exit 1
}

Write-Host "📊 Loading audit report..." -ForegroundColor Yellow
$report = Get-Content $reportPath -Raw | ConvertFrom-Json

Write-Host "✅ Loaded $($report.modules.Count) modules" -ForegroundColor Green
Write-Host ""

# Filter modules
Write-Host "🔎 Filtering modules..." -ForegroundColor Yellow
Write-Host "   Types: $($Types -join ', ')" -ForegroundColor Gray
Write-Host "   Min LOC: $MinLOC" -ForegroundColor Gray
Write-Host "   Status: 🟢 ALIVE only" -ForegroundColor Gray
Write-Host ""

$topModules = $report.modules | Where-Object {
    $_.status -eq "🟢 ALIVE" -and
    $_.type -in $Types -and
    $_.loc -ge $MinLOC
} | Sort-Object -Property loc -Descending | Select-Object -First $TopCount

Write-Host "✅ Found $($topModules.Count) top modules" -ForegroundColor Green
Write-Host ""

# Group by type
$grouped = $topModules | Group-Object -Property type | Sort-Object -Property Count -Descending

# Generate markdown report
$markdown = @"
# 🏆 QANTUM Top $TopCount Enterprise Modules

**Generated:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")  
**Total Modules Analyzed:** $($report.modules.Count)  
**Filtered Modules:** $($topModules.Count)  
**Filter Criteria:** Types = [$($Types -join ', ')], Min LOC = $MinLOC, Status = 🟢 ALIVE

---

## 📊 Statistics by Type

| Type | Count | Total LOC |
|------|-------|-----------|
"@

foreach ($group in $grouped) {
    $totalLOC = ($group.Group | Measure-Object -Property loc -Sum).Sum
    $markdown += "`n| **$($group.Name)** | $($group.Count) | $($totalLOC.ToString('N0')) |"
}

$markdown += @"


---

## 🎯 Top Modules by Category

"@

foreach ($group in $grouped) {
    $markdown += "`n### $($group.Name) ($($group.Count) modules)`n`n"
    
    foreach ($module in $group.Group | Select-Object -First 10) {
        $markdown += "#### ``$($module.id)`` - $($module.loc) LOC`n`n"
        $markdown += "**Path:** ``$($module.path)```n`n"
        
        if ($module.exports -and $module.exports.Count -gt 0) {
            $markdown += "**Exports:**`n"
            foreach ($export in $module.exports | Select-Object -First 5) {
                $markdown += "- ``$export```n"
            }
            if ($module.exports.Count -gt 5) {
                $markdown += "- *(+$($module.exports.Count - 5) more)*`n"
            }
            $markdown += "`n"
        }
        
        $markdown += "---`n`n"
    }
}

# Add integration recommendations
$markdown += @"

## 💡 Integration Recommendations for QANTUM Framework

Based on the top modules, here are suggested enhancements:

### 1. Security Layer Upgrades
"@

$securityModules = $topModules | Where-Object { $_.type -eq "Security" } | Select-Object -First 5
foreach ($mod in $securityModules) {
    $markdown += "`n- **$($mod.id)** ($($mod.loc) LOC) - Enhance security posture"
}

$markdown += @"


### 2. God-Tier Features
"@

$godTierModules = $topModules | Where-Object { $_.type -eq "God-Tier" } | Select-Object -First 5
foreach ($mod in $godTierModules) {
    $markdown += "`n- **$($mod.id)** ($($mod.loc) LOC) - Add enterprise capabilities"
}

$markdown += @"


### 3. Core Infrastructure
"@

$coreModules = $topModules | Where-Object { $_.type -eq "Core" } | Select-Object -First 5
foreach ($mod in $coreModules) {
    $markdown += "`n- **$($mod.id)** ($($mod.loc) LOC) - Strengthen foundation"
}

$markdown += @"


---

## 📋 Full Module List (Top $TopCount)

| # | Module ID | Type | LOC | Exports |
|---|-----------|------|-----|---------|
"@

$counter = 1
foreach ($module in $topModules) {
    $exportCount = if ($module.exports) { $module.exports.Count } else { 0 }
    $markdown += "`n| $counter | ``$($module.id)`` | $($module.type) | $($module.loc) | $exportCount |"
    $counter++
}

$markdown += @"


---

**Generated by QANTUM Module Analyzer**  
**Command:** ``./analyze-modules.ps1 -TopCount $TopCount -MinLOC $MinLOC``
"@

# Save report
$markdown | Out-File -FilePath $outputPath -Encoding UTF8
Write-Host "✅ Report saved to: $outputPath" -ForegroundColor Green

# Display summary
Write-Host ""
Write-Host "📊 Summary:" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
foreach ($group in $grouped) {
    $totalLOC = ($group.Group | Measure-Object -Property loc -Sum).Sum
    Write-Host "  $($group.Name): $($group.Count) modules, $($totalLOC.ToString('N0')) LOC" -ForegroundColor White
}
Write-Host ""
Write-Host "🎉 Analysis complete! Check TOP_MODULES.md for full report." -ForegroundColor Green
